/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {CountryDetails} from './CountryDetails';
import {TimeoffsetDetails} from './TimeoffsetDetails';

/**
 * The AddressWithDetails model module.
 * @module model/AddressWithDetails
 * @version 1.0.0
 */
export class AddressWithDetails {
  /**
   * Constructs a new <code>AddressWithDetails</code>.
   * Details of the registered address.
   * @alias module:model/AddressWithDetails
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>AddressWithDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddressWithDetails} obj Optional instance to populate.
   * @return {module:model/AddressWithDetails} The populated <code>AddressWithDetails</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddressWithDetails();
      if (data.hasOwnProperty('address_line1'))
        obj.addressLine1 = ApiClient.convertToType(data['address_line1'], 'String');
      if (data.hasOwnProperty('address_line2'))
        obj.addressLine2 = ApiClient.convertToType(data['address_line2'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('region_id'))
        obj.regionId = ApiClient.convertToType(data['region_id'], 'Number');
      if (data.hasOwnProperty('region_name'))
        obj.regionName = ApiClient.convertToType(data['region_name'], 'String');
      if (data.hasOwnProperty('region_code'))
        obj.regionCode = ApiClient.convertToType(data['region_code'], 'String');
      if (data.hasOwnProperty('post_code'))
        obj.postCode = ApiClient.convertToType(data['post_code'], 'String');
      if (data.hasOwnProperty('landline'))
        obj.landline = ApiClient.convertToType(data['landline'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('company'))
        obj.company = ApiClient.convertToType(data['company'], 'String');
      if (data.hasOwnProperty('country_details'))
        obj.countryDetails = CountryDetails.constructFromObject(data['country_details']);
      if (data.hasOwnProperty('timeoffset_details'))
        obj.timeoffsetDetails = TimeoffsetDetails.constructFromObject(data['timeoffset_details']);
      if (data.hasOwnProperty('state_id'))
        obj.stateId = ApiClient.convertToType(data['state_id'], 'String');
    }
    return obj;
  }
}

/**
 * Address line 1
 * @member {String} addressLine1
 */
AddressWithDetails.prototype.addressLine1 = undefined;

/**
 * Address line 2
 * @member {String} addressLine2
 */
AddressWithDetails.prototype.addressLine2 = undefined;

/**
 * City
 * @member {String} city
 */
AddressWithDetails.prototype.city = undefined;

/**
 * Country ISO 3166-1 code
 * @member {String} country
 */
AddressWithDetails.prototype.country = undefined;

/**
 * Country region id
 * @member {Number} regionId
 */
AddressWithDetails.prototype.regionId = undefined;

/**
 * Region name
 * @member {String} regionName
 */
AddressWithDetails.prototype.regionName = undefined;

/**
 * Region code
 * @member {String} regionCode
 */
AddressWithDetails.prototype.regionCode = undefined;

/**
 * Postal code
 * @member {String} postCode
 */
AddressWithDetails.prototype.postCode = undefined;

/**
 * Landline number
 * @member {String} landline
 */
AddressWithDetails.prototype.landline = undefined;

/**
 * undefined
 * @member {String} firstName
 */
AddressWithDetails.prototype.firstName = undefined;

/**
 * undefined
 * @member {String} lastName
 */
AddressWithDetails.prototype.lastName = undefined;

/**
 * undefined
 * @member {String} company
 */
AddressWithDetails.prototype.company = undefined;

/**
 * @member {module:model/CountryDetails} countryDetails
 */
AddressWithDetails.prototype.countryDetails = undefined;

/**
 * @member {module:model/TimeoffsetDetails} timeoffsetDetails
 */
AddressWithDetails.prototype.timeoffsetDetails = undefined;

/**
 * undefined
 * @member {String} stateId
 */
AddressWithDetails.prototype.stateId = undefined;

