/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The AddressPayload model module.
 * @module model/AddressPayload
 * @version 1.0.0
 */
export class AddressPayload {
  /**
   * Constructs a new <code>AddressPayload</code>.
   * Account&#x27;s personal address
   * @alias module:model/AddressPayload
   * @class
   * @param addressLine1 {String} Address line 1
   * @param city {String} City
   * @param country {String} Country ISO 3166-1 code
   * @param postCode {String} Postal code
   */
  constructor(addressLine1, city, country, postCode) {
    this.addressLine1 = addressLine1;
    this.city = city;
    this.country = country;
    this.postCode = postCode;
  }

  /**
   * Constructs a <code>AddressPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AddressPayload} obj Optional instance to populate.
   * @return {module:model/AddressPayload} The populated <code>AddressPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new AddressPayload();
      if (data.hasOwnProperty('address_line1'))
        obj.addressLine1 = ApiClient.convertToType(data['address_line1'], 'String');
      if (data.hasOwnProperty('address_line2'))
        obj.addressLine2 = ApiClient.convertToType(data['address_line2'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('region_id'))
        obj.regionId = ApiClient.convertToType(data['region_id'], 'Number');
      if (data.hasOwnProperty('region_name'))
        obj.regionName = ApiClient.convertToType(data['region_name'], 'String');
      if (data.hasOwnProperty('post_code'))
        obj.postCode = ApiClient.convertToType(data['post_code'], 'String');
      if (data.hasOwnProperty('landline'))
        obj.landline = ApiClient.convertToType(data['landline'], 'String');
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('company'))
        obj.company = ApiClient.convertToType(data['company'], 'String');
    }
    return obj;
  }
}

/**
 * Address line 1
 * @member {String} addressLine1
 */
AddressPayload.prototype.addressLine1 = undefined;

/**
 * Address line 2
 * @member {String} addressLine2
 */
AddressPayload.prototype.addressLine2 = undefined;

/**
 * City
 * @member {String} city
 */
AddressPayload.prototype.city = undefined;

/**
 * Country ISO 3166-1 code
 * @member {String} country
 */
AddressPayload.prototype.country = undefined;

/**
 * Country region id
 * @member {Number} regionId
 */
AddressPayload.prototype.regionId = undefined;

/**
 * Country region name
 * @member {String} regionName
 */
AddressPayload.prototype.regionName = undefined;

/**
 * Postal code
 * @member {String} postCode
 */
AddressPayload.prototype.postCode = undefined;

/**
 * Landline number
 * @member {String} landline
 */
AddressPayload.prototype.landline = undefined;

/**
 * First name
 * @member {String} firstName
 */
AddressPayload.prototype.firstName = undefined;

/**
 * Last name
 * @member {String} lastName
 */
AddressPayload.prototype.lastName = undefined;

/**
 * Company name
 * @member {String} company
 */
AddressPayload.prototype.company = undefined;

