/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The BankAccountPayload model module.
 * @module model/BankAccountPayload
 * @version 1.0.0
 */
export class BankAccountPayload {
  /**
   * Constructs a new <code>BankAccountPayload</code>.
   * @alias module:model/BankAccountPayload
   * @class
   * @param iban {String} IBAN
   * @param swift {String} SWIFT code
   * @param accountHolderName {String} Account holder name
   */
  constructor(iban, swift, accountHolderName) {
    this.iban = iban;
    this.swift = swift;
    this.accountHolderName = accountHolderName;
  }

  /**
   * Constructs a <code>BankAccountPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BankAccountPayload} obj Optional instance to populate.
   * @return {module:model/BankAccountPayload} The populated <code>BankAccountPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new BankAccountPayload();
      if (data.hasOwnProperty('bank_code'))
        obj.bankCode = ApiClient.convertToType(data['bank_code'], 'String');
      if (data.hasOwnProperty('branch_code'))
        obj.branchCode = ApiClient.convertToType(data['branch_code'], 'String');
      if (data.hasOwnProperty('account_number'))
        obj.accountNumber = ApiClient.convertToType(data['account_number'], 'String');
      if (data.hasOwnProperty('iban'))
        obj.iban = ApiClient.convertToType(data['iban'], 'String');
      if (data.hasOwnProperty('swift'))
        obj.swift = ApiClient.convertToType(data['swift'], 'String');
      if (data.hasOwnProperty('account_type'))
        obj.accountType = ApiClient.convertToType(data['account_type'], 'String');
      if (data.hasOwnProperty('account_holder_name'))
        obj.accountHolderName = ApiClient.convertToType(data['account_holder_name'], 'String');
      if (data.hasOwnProperty('check_digit'))
        obj.checkDigit = ApiClient.convertToType(data['check_digit'], 'String');
      if (data.hasOwnProperty('primary'))
        obj.primary = ApiClient.convertToType(data['primary'], 'Boolean');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('account_category'))
        obj.accountCategory = ApiClient.convertToType(data['account_category'], 'String');
    }
    return obj;
  }
}

/**
 * Bank code
 * @member {String} bankCode
 */
BankAccountPayload.prototype.bankCode = undefined;

/**
 * Branch code
 * @member {String} branchCode
 */
BankAccountPayload.prototype.branchCode = undefined;

/**
 * Account number
 * @member {String} accountNumber
 */
BankAccountPayload.prototype.accountNumber = undefined;

/**
 * IBAN
 * @member {String} iban
 */
BankAccountPayload.prototype.iban = undefined;

/**
 * SWIFT code
 * @member {String} swift
 */
BankAccountPayload.prototype.swift = undefined;

/**
 * Allowed values for the <code>accountType</code> property.
 * @enum {String}
 * @readonly
 */
BankAccountPayload.AccountTypeEnum = {
  /**
   * value: "CURRENT"
   * @const
   */
  CURRENT: "CURRENT",

  /**
   * value: "SAVINGS"
   * @const
   */
  SAVINGS: "SAVINGS"
};
/**
 * Type of the account.
 * @member {module:model/BankAccountPayload.AccountTypeEnum} accountType
 */
BankAccountPayload.prototype.accountType = undefined;

/**
 * Account holder name
 * @member {String} accountHolderName
 */
BankAccountPayload.prototype.accountHolderName = undefined;

/**
 * Check digit
 * @member {String} checkDigit
 */
BankAccountPayload.prototype.checkDigit = undefined;

/**
 * Determines if this bank account will be primary. Default is false
 * @member {Boolean} primary
 */
BankAccountPayload.prototype.primary = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
BankAccountPayload.StatusEnum = {
  /**
   * value: "OPEN"
   * @const
   */
  OPEN: "OPEN"
};
/**
 * Determines the bank account status.
 * @member {module:model/BankAccountPayload.StatusEnum} status
 */
BankAccountPayload.prototype.status = undefined;

/**
 * Allowed values for the <code>accountCategory</code> property.
 * @enum {String}
 * @readonly
 */
BankAccountPayload.AccountCategoryEnum = {
  /**
   * value: "PERSONAL"
   * @const
   */
  PERSONAL: "PERSONAL",

  /**
   * value: "BUSINESS"
   * @const
   */
  BUSINESS: "BUSINESS"
};
/**
 * Determines if this bank account is business or personal.
 * @member {module:model/BankAccountPayload.AccountCategoryEnum} accountCategory
 */
BankAccountPayload.prototype.accountCategory = undefined;

