/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Checkout} from './Checkout';
import {CheckoutSuccessPaymentInstrument} from './CheckoutSuccessPaymentInstrument';
import {Currency} from './Currency';
import {MandateResponse} from './MandateResponse';

/**
 * The CheckoutSuccess model module.
 * @module model/CheckoutSuccess
 * @version 1.0.0
 */
export class CheckoutSuccess extends Checkout {
  /**
   * Constructs a new <code>CheckoutSuccess</code>.
   * @alias module:model/CheckoutSuccess
   * @class
   * @extends module:model/Checkout
   */
  constructor() {
    super();
  }

  /**
   * Constructs a <code>CheckoutSuccess</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckoutSuccess} obj Optional instance to populate.
   * @return {module:model/CheckoutSuccess} The populated <code>CheckoutSuccess</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckoutSuccess();
      Checkout.constructFromObject(data, obj);
      if (data.hasOwnProperty('checkout_reference'))
        obj.checkoutReference = ApiClient.convertToType(data['checkout_reference'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = Currency.constructFromObject(data['currency']);
      if (data.hasOwnProperty('pay_to_email'))
        obj.payToEmail = ApiClient.convertToType(data['pay_to_email'], 'String');
      if (data.hasOwnProperty('merchant_code'))
        obj.merchantCode = ApiClient.convertToType(data['merchant_code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('transaction_code'))
        obj.transactionCode = ApiClient.convertToType(data['transaction_code'], 'String');
      if (data.hasOwnProperty('transaction_id'))
        obj.transactionId = ApiClient.convertToType(data['transaction_id'], 'String');
      if (data.hasOwnProperty('merchant_name'))
        obj.merchantName = ApiClient.convertToType(data['merchant_name'], 'String');
      if (data.hasOwnProperty('redirect_url'))
        obj.redirectUrl = ApiClient.convertToType(data['redirect_url'], 'String');
      if (data.hasOwnProperty('customer_id'))
        obj.customerId = ApiClient.convertToType(data['customer_id'], 'String');
      if (data.hasOwnProperty('payment_instrument'))
        obj.paymentInstrument = CheckoutSuccessPaymentInstrument.constructFromObject(data['payment_instrument']);
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [Object]);
    }
    return obj;
  }
}

/**
 * Unique ID of the payment checkout specified by the client application when creating the checkout resource.
 * @member {String} checkoutReference
 */
CheckoutSuccess.prototype.checkoutReference = undefined;

/**
 * Amount of the payment.
 * @member {Number} amount
 */
CheckoutSuccess.prototype.amount = undefined;

/**
 * @member {module:model/Currency} currency
 */
CheckoutSuccess.prototype.currency = undefined;

/**
 * Email address of the registered user (merchant) to whom the payment is made. It is highly recommended to use `merchant_code` instead of `pay_to_email`.
 * @member {String} payToEmail
 */
CheckoutSuccess.prototype.payToEmail = undefined;

/**
 * Unique identifying code of the merchant profile.
 * @member {String} merchantCode
 */
CheckoutSuccess.prototype.merchantCode = undefined;

/**
 * Short description of the checkout visible in the SumUp dashboard. The description can contribute to reporting, allowing easier identification of a checkout.
 * @member {String} description
 */
CheckoutSuccess.prototype.description = undefined;

/**
 * Unique ID of the checkout resource.
 * @member {String} id
 */
CheckoutSuccess.prototype.id = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
CheckoutSuccess.StatusEnum = {
  /**
   * value: "PENDING"
   * @const
   */
  PENDING: "PENDING",

  /**
   * value: "FAILED"
   * @const
   */
  FAILED: "FAILED",

  /**
   * value: "PAID"
   * @const
   */
  PAID: "PAID"
};
/**
 * Currrent status of the checkout.
 * @member {module:model/CheckoutSuccess.StatusEnum} status
 */
CheckoutSuccess.prototype.status = undefined;

/**
 * Date and time of the creation of the payment checkout. Response format expressed according to <a href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\" rel=\"noopener\">ISO8601</a> code.
 * @member {Date} _date
 */
CheckoutSuccess.prototype._date = undefined;

/**
 * Transaction code of the successful transaction with which the payment for the checkout is completed.
 * @member {String} transactionCode
 */
CheckoutSuccess.prototype.transactionCode = undefined;

/**
 * Transaction ID of the successful transaction with which the payment for the checkout is completed.
 * @member {String} transactionId
 */
CheckoutSuccess.prototype.transactionId = undefined;

/**
 * Name of the merchant
 * @member {String} merchantName
 */
CheckoutSuccess.prototype.merchantName = undefined;

/**
 * Refers to a url where the end user is redirected once the payment processing completes.
 * @member {String} redirectUrl
 */
CheckoutSuccess.prototype.redirectUrl = undefined;

/**
 * Unique identification of a customer. If specified, the checkout session and payment instrument are associated with the referrenced customer.
 * @member {String} customerId
 */
CheckoutSuccess.prototype.customerId = undefined;

/**
 * @member {module:model/CheckoutSuccessPaymentInstrument} paymentInstrument
 */
CheckoutSuccess.prototype.paymentInstrument = undefined;

/**
 * List of transactions related to the payment.
 * @member {Array.<Object>} transactions
 */
CheckoutSuccess.prototype.transactions = undefined;

