/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Currency} from './Currency';
import {MandateResponse} from './MandateResponse';

/**
 * The Checkout model module.
 * @module model/Checkout
 * @version 1.0.0
 */
export class Checkout {
  /**
   * Constructs a new <code>Checkout</code>.
   * Details of the payment checkout.
   * @alias module:model/Checkout
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Checkout</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Checkout} obj Optional instance to populate.
   * @return {module:model/Checkout} The populated <code>Checkout</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Checkout();
      if (data.hasOwnProperty('checkout_reference'))
        obj.checkoutReference = ApiClient.convertToType(data['checkout_reference'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = Currency.constructFromObject(data['currency']);
      if (data.hasOwnProperty('pay_to_email'))
        obj.payToEmail = ApiClient.convertToType(data['pay_to_email'], 'String');
      if (data.hasOwnProperty('merchant_code'))
        obj.merchantCode = ApiClient.convertToType(data['merchant_code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('return_url'))
        obj.returnUrl = ApiClient.convertToType(data['return_url'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('valid_until'))
        obj.validUntil = ApiClient.convertToType(data['valid_until'], 'Date');
      if (data.hasOwnProperty('customer_id'))
        obj.customerId = ApiClient.convertToType(data['customer_id'], 'String');
      if (data.hasOwnProperty('mandate'))
        obj.mandate = MandateResponse.constructFromObject(data['mandate']);
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [AllOfCheckoutTransactionsItems]);
    }
    return obj;
  }
}

/**
 * Unique ID of the payment checkout specified by the client application when creating the checkout resource.
 * @member {String} checkoutReference
 */
Checkout.prototype.checkoutReference = undefined;

/**
 * Amount of the payment.
 * @member {Number} amount
 */
Checkout.prototype.amount = undefined;

/**
 * @member {module:model/Currency} currency
 */
Checkout.prototype.currency = undefined;

/**
 * Email address of the registered user (merchant) to whom the payment is made.
 * @member {String} payToEmail
 */
Checkout.prototype.payToEmail = undefined;

/**
 * Unique identifying code of the merchant profile.
 * @member {String} merchantCode
 */
Checkout.prototype.merchantCode = undefined;

/**
 * Short description of the checkout visible in the SumUp dashboard. The description can contribute to reporting, allowing easier identification of a checkout.
 * @member {String} description
 */
Checkout.prototype.description = undefined;

/**
 * URL to which the SumUp platform sends the processing status of the payment checkout.
 * @member {String} returnUrl
 */
Checkout.prototype.returnUrl = undefined;

/**
 * Unique ID of the checkout resource.
 * @member {String} id
 */
Checkout.prototype.id = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Checkout.StatusEnum = {
  /**
   * value: "PENDING"
   * @const
   */
  PENDING: "PENDING",

  /**
   * value: "FAILED"
   * @const
   */
  FAILED: "FAILED",

  /**
   * value: "PAID"
   * @const
   */
  PAID: "PAID"
};
/**
 * Currrent status of the checkout.
 * @member {module:model/Checkout.StatusEnum} status
 */
Checkout.prototype.status = undefined;

/**
 * Date and time of the creation of the payment checkout. Response format expressed according to <a href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\" rel=\"noopener\">ISO8601</a> code.
 * @member {Date} _date
 */
Checkout.prototype._date = undefined;

/**
 * Date and time of the checkout expiration before which the client application needs to send a processing request. If no value is present, the checkout does not have an expiration time.
 * @member {Date} validUntil
 */
Checkout.prototype.validUntil = undefined;

/**
 * Unique identification of a customer. If specified, the checkout session and payment instrument are associated with the referrenced customer.
 * @member {String} customerId
 */
Checkout.prototype.customerId = undefined;

/**
 * @member {module:model/MandateResponse} mandate
 */
Checkout.prototype.mandate = undefined;

/**
 * List of transactions related to the payment.
 * @member {Array.<Object>} transactions
 */
Checkout.prototype.transactions = undefined;

