/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The CheckoutAcceptedNextStepPayload model module.
 * @module model/CheckoutAcceptedNextStepPayload
 * @version 1.0.0
 */
export class CheckoutAcceptedNextStepPayload {
  /**
   * Constructs a new <code>CheckoutAcceptedNextStepPayload</code>.
   * Contains parameters essential for form redirection. Number of object keys and their content can vary.
   * @alias module:model/CheckoutAcceptedNextStepPayload
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>CheckoutAcceptedNextStepPayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CheckoutAcceptedNextStepPayload} obj Optional instance to populate.
   * @return {module:model/CheckoutAcceptedNextStepPayload} The populated <code>CheckoutAcceptedNextStepPayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new CheckoutAcceptedNextStepPayload();
      if (data.hasOwnProperty('PaReq'))
        obj.paReq = ApiClient.convertToType(data['PaReq'], Object);
      if (data.hasOwnProperty('MD'))
        obj.MD = ApiClient.convertToType(data['MD'], Object);
      if (data.hasOwnProperty('TermUrl'))
        obj.termUrl = ApiClient.convertToType(data['TermUrl'], Object);
    }
    return obj;
  }
}

/**
 * @member {Object} paReq
 */
CheckoutAcceptedNextStepPayload.prototype.paReq = undefined;

/**
 * @member {Object} MD
 */
CheckoutAcceptedNextStepPayload.prototype.MD = undefined;

/**
 * @member {Object} termUrl
 */
CheckoutAcceptedNextStepPayload.prototype.termUrl = undefined;

