/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {DoingBusinessAsAddress} from './DoingBusinessAsAddress';

/**
 * The DoingBusinessAs model module.
 * @module model/DoingBusinessAs
 * @version 1.0.0
 */
export class DoingBusinessAs {
  /**
   * Constructs a new <code>DoingBusinessAs</code>.
   * Doing Business As information
   * @alias module:model/DoingBusinessAs
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DoingBusinessAs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DoingBusinessAs} obj Optional instance to populate.
   * @return {module:model/DoingBusinessAs} The populated <code>DoingBusinessAs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DoingBusinessAs();
      if (data.hasOwnProperty('business_name'))
        obj.businessName = ApiClient.convertToType(data['business_name'], 'String');
      if (data.hasOwnProperty('company_registration_number'))
        obj.companyRegistrationNumber = ApiClient.convertToType(data['company_registration_number'], 'String');
      if (data.hasOwnProperty('vat_id'))
        obj.vatId = ApiClient.convertToType(data['vat_id'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = DoingBusinessAsAddress.constructFromObject(data['address']);
    }
    return obj;
  }
}

/**
 * Doing business as name
 * @member {String} businessName
 */
DoingBusinessAs.prototype.businessName = undefined;

/**
 * Doing business as company registration number
 * @member {String} companyRegistrationNumber
 */
DoingBusinessAs.prototype.companyRegistrationNumber = undefined;

/**
 * Doing business as vat id
 * @member {String} vatId
 */
DoingBusinessAs.prototype.vatId = undefined;

/**
 * Doing business as website
 * @member {String} website
 */
DoingBusinessAs.prototype.website = undefined;

/**
 * Doing business as email
 * @member {String} email
 */
DoingBusinessAs.prototype.email = undefined;

/**
 * @member {module:model/DoingBusinessAsAddress} address
 */
DoingBusinessAs.prototype.address = undefined;

