/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The DoingBusinessAsAddress model module.
 * @module model/DoingBusinessAsAddress
 * @version 1.0.0
 */
export class DoingBusinessAsAddress {
  /**
   * Constructs a new <code>DoingBusinessAsAddress</code>.
   * @alias module:model/DoingBusinessAsAddress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>DoingBusinessAsAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DoingBusinessAsAddress} obj Optional instance to populate.
   * @return {module:model/DoingBusinessAsAddress} The populated <code>DoingBusinessAsAddress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new DoingBusinessAsAddress();
      if (data.hasOwnProperty('address_line1'))
        obj.addressLine1 = ApiClient.convertToType(data['address_line1'], 'String');
      if (data.hasOwnProperty('address_line2'))
        obj.addressLine2 = ApiClient.convertToType(data['address_line2'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('region_id'))
        obj.regionId = ApiClient.convertToType(data['region_id'], 'Number');
      if (data.hasOwnProperty('region_name'))
        obj.regionName = ApiClient.convertToType(data['region_name'], 'String');
      if (data.hasOwnProperty('post_code'))
        obj.postCode = ApiClient.convertToType(data['post_code'], 'String');
    }
    return obj;
  }
}

/**
 * Address line 1
 * @member {String} addressLine1
 */
DoingBusinessAsAddress.prototype.addressLine1 = undefined;

/**
 * Address line 2
 * @member {String} addressLine2
 */
DoingBusinessAsAddress.prototype.addressLine2 = undefined;

/**
 * City
 * @member {String} city
 */
DoingBusinessAsAddress.prototype.city = undefined;

/**
 * Country ISO 3166-1 code
 * @member {String} country
 */
DoingBusinessAsAddress.prototype.country = undefined;

/**
 * Country region id
 * @member {Number} regionId
 */
DoingBusinessAsAddress.prototype.regionId = undefined;

/**
 * Country region name
 * @member {String} regionName
 */
DoingBusinessAsAddress.prototype.regionName = undefined;

/**
 * Postal code
 * @member {String} postCode
 */
DoingBusinessAsAddress.prototype.postCode = undefined;

