/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The FinancialTransactionsInner model module.
 * @module model/FinancialTransactionsInner
 * @version 1.0.0
 */
export class FinancialTransactionsInner {
  /**
   * Constructs a new <code>FinancialTransactionsInner</code>.
   * @alias module:model/FinancialTransactionsInner
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>FinancialTransactionsInner</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FinancialTransactionsInner} obj Optional instance to populate.
   * @return {module:model/FinancialTransactionsInner} The populated <code>FinancialTransactionsInner</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new FinancialTransactionsInner();
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = ApiClient.convertToType(data['currency'], 'String');
      if (data.hasOwnProperty('external_reference'))
        obj.externalReference = ApiClient.convertToType(data['external_reference'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = ApiClient.convertToType(data['timestamp'], 'String');
      if (data.hasOwnProperty('transaction_code'))
        obj.transactionCode = ApiClient.convertToType(data['transaction_code'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} amount
 */
FinancialTransactionsInner.prototype.amount = undefined;

/**
 * @member {String} currency
 */
FinancialTransactionsInner.prototype.currency = undefined;

/**
 * @member {String} externalReference
 */
FinancialTransactionsInner.prototype.externalReference = undefined;

/**
 * @member {String} id
 */
FinancialTransactionsInner.prototype.id = undefined;

/**
 * @member {String} timestamp
 */
FinancialTransactionsInner.prototype.timestamp = undefined;

/**
 * @member {String} transactionCode
 */
FinancialTransactionsInner.prototype.transactionCode = undefined;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
FinancialTransactionsInner.TypeEnum = {
  /**
   * value: "SALE"
   * @const
   */
  SALE: "SALE",

  /**
   * value: "REFUND"
   * @const
   */
  REFUND: "REFUND",

  /**
   * value: "CHARGE_BACK"
   * @const
   */
  CHARGE_BACK: "CHARGE_BACK",

  /**
   * value: "DD_RETURN"
   * @const
   */
  DD_RETURN: "DD_RETURN",

  /**
   * value: "DD_RETURN_REVERSAL"
   * @const
   */
  DD_RETURN_REVERSAL: "DD_RETURN_REVERSAL"
};
/**
 * @member {module:model/FinancialTransactionsInner.TypeEnum} type
 */
FinancialTransactionsInner.prototype.type = undefined;

