/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Currency} from './Currency';

/**
 * The InlineResponse2001 model module.
 * @module model/InlineResponse2001
 * @version 1.0.0
 */
export class InlineResponse2001 {
  /**
   * Constructs a new <code>InlineResponse2001</code>.
   * Details of the deleted checkout.
   * @alias module:model/InlineResponse2001
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>InlineResponse2001</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse2001} obj Optional instance to populate.
   * @return {module:model/InlineResponse2001} The populated <code>InlineResponse2001</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new InlineResponse2001();
      if (data.hasOwnProperty('checkout_reference'))
        obj.checkoutReference = ApiClient.convertToType(data['checkout_reference'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('amount'))
        obj.amount = ApiClient.convertToType(data['amount'], 'Number');
      if (data.hasOwnProperty('currency'))
        obj.currency = Currency.constructFromObject(data['currency']);
      if (data.hasOwnProperty('pay_to_email'))
        obj.payToEmail = ApiClient.convertToType(data['pay_to_email'], 'String');
      if (data.hasOwnProperty('merchant_code'))
        obj.merchantCode = ApiClient.convertToType(data['merchant_code'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('purpose'))
        obj.purpose = ApiClient.convertToType(data['purpose'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('valid_until'))
        obj.validUntil = ApiClient.convertToType(data['valid_until'], 'Date');
      if (data.hasOwnProperty('merchant_name'))
        obj.merchantName = ApiClient.convertToType(data['merchant_name'], 'String');
      if (data.hasOwnProperty('transactions'))
        obj.transactions = ApiClient.convertToType(data['transactions'], [AllOfinlineResponse2001TransactionsItems]);
    }
    return obj;
  }
}

/**
 * Unique ID of the payment checkout specified by the client application when creating the checkout resource.
 * @member {String} checkoutReference
 */
InlineResponse2001.prototype.checkoutReference = undefined;

/**
 * Unique ID of the checkout resource.
 * @member {String} id
 */
InlineResponse2001.prototype.id = undefined;

/**
 * Amount of the payment.
 * @member {Number} amount
 */
InlineResponse2001.prototype.amount = undefined;

/**
 * @member {module:model/Currency} currency
 */
InlineResponse2001.prototype.currency = undefined;

/**
 * Email address of the registered user (merchant) to whom the payment is made. It is highly recommended to use `merchant_code` instead of `pay_to_email`.
 * @member {String} payToEmail
 */
InlineResponse2001.prototype.payToEmail = undefined;

/**
 * Unique identifying code of the merchant profile.
 * @member {String} merchantCode
 */
InlineResponse2001.prototype.merchantCode = undefined;

/**
 * Short description of the checkout visible in the SumUp dashboard. The description can contribute to reporting, allowing easier identification of a checkout.
 * @member {String} description
 */
InlineResponse2001.prototype.description = undefined;

/**
 * Allowed values for the <code>purpose</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2001.PurposeEnum = {
  /**
   * value: "SETUP_RECURRING_PAYMENT"
   * @const
   */
  SETUP_RECURRING_PAYMENT: "SETUP_RECURRING_PAYMENT",

  /**
   * value: "CHECKOUT"
   * @const
   */
  CHECKOUT: "CHECKOUT"
};
/**
 * Purpose of the checkout creation initially
 * @member {module:model/InlineResponse2001.PurposeEnum} purpose
 */
InlineResponse2001.prototype.purpose = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
InlineResponse2001.StatusEnum = {
  /**
   * value: "EXPIRED"
   * @const
   */
  EXPIRED: "EXPIRED"
};
/**
 * Currrent status of the checkout.
 * @member {module:model/InlineResponse2001.StatusEnum} status
 */
InlineResponse2001.prototype.status = undefined;

/**
 * Date and time of the creation of the payment checkout. Response format expressed according to <a href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\" rel=\"noopener\">ISO8601</a> code.
 * @member {Date} _date
 */
InlineResponse2001.prototype._date = undefined;

/**
 * Date and time of the checkout expiration before which the client application needs to send a processing request. If no value is present, the checkout does not have an expiration time.
 * @member {Date} validUntil
 */
InlineResponse2001.prototype.validUntil = undefined;

/**
 * Merchant name
 * @member {String} merchantName
 */
InlineResponse2001.prototype.merchantName = undefined;

/**
 * List of transactions related to the payment.
 * @member {Array.<Object>} transactions
 */
InlineResponse2001.prototype.transactions = undefined;

