/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Link model module.
 * @module model/Link
 * @version 1.0.0
 */
export class Link {
  /**
   * Constructs a new <code>Link</code>.
   * Details of a link to a related resource.
   * @alias module:model/Link
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Link</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Link} obj Optional instance to populate.
   * @return {module:model/Link} The populated <code>Link</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Link();
      if (data.hasOwnProperty('rel'))
        obj.rel = ApiClient.convertToType(data['rel'], 'String');
      if (data.hasOwnProperty('href'))
        obj.href = ApiClient.convertToType(data['href'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
    }
    return obj;
  }
}

/**
 * Specifies the relation to the current resource.
 * @member {String} rel
 */
Link.prototype.rel = undefined;

/**
 * URL for accessing the related resource.
 * @member {String} href
 */
Link.prototype.href = undefined;

/**
 * Specifies the media type of the related resource.
 * @member {String} type
 */
Link.prototype.type = undefined;

