/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Account} from './Account';
import {AppSettings} from './AppSettings';
import {MerchantProfile} from './MerchantProfile';
import {Operators} from './Operators';
import {Permissions} from './Permissions';
import {PersonalProfile} from './PersonalProfile';

/**
 * The MerchantAccount model module.
 * @module model/MerchantAccount
 * @version 1.0.0
 */
export class MerchantAccount {
  /**
   * Constructs a new <code>MerchantAccount</code>.
   * Details of user account.
   * @alias module:model/MerchantAccount
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MerchantAccount</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MerchantAccount} obj Optional instance to populate.
   * @return {module:model/MerchantAccount} The populated <code>MerchantAccount</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MerchantAccount();
      if (data.hasOwnProperty('account'))
        obj.account = Account.constructFromObject(data['account']);
      if (data.hasOwnProperty('personal_profile'))
        obj.personalProfile = PersonalProfile.constructFromObject(data['personal_profile']);
      if (data.hasOwnProperty('merchant_profile'))
        obj.merchantProfile = MerchantProfile.constructFromObject(data['merchant_profile']);
      if (data.hasOwnProperty('operators'))
        obj.operators = Operators.constructFromObject(data['operators']);
      if (data.hasOwnProperty('app_settings'))
        obj.appSettings = AppSettings.constructFromObject(data['app_settings']);
      if (data.hasOwnProperty('permissions'))
        obj.permissions = Permissions.constructFromObject(data['permissions']);
      if (data.hasOwnProperty('is_migrated_payleven_br'))
        obj.isMigratedPaylevenBr = ApiClient.convertToType(data['is_migrated_payleven_br'], 'Boolean');
    }
    return obj;
  }
}

/**
 * @member {module:model/Account} account
 */
MerchantAccount.prototype.account = undefined;

/**
 * @member {module:model/PersonalProfile} personalProfile
 */
MerchantAccount.prototype.personalProfile = undefined;

/**
 * @member {module:model/MerchantProfile} merchantProfile
 */
MerchantAccount.prototype.merchantProfile = undefined;

/**
 * @member {module:model/Operators} operators
 */
MerchantAccount.prototype.operators = undefined;

/**
 * @member {module:model/AppSettings} appSettings
 */
MerchantAccount.prototype.appSettings = undefined;

/**
 * @member {module:model/Permissions} permissions
 */
MerchantAccount.prototype.permissions = undefined;

/**
 * Merchant comes from payleven BR migration
 * @member {Boolean} isMigratedPaylevenBr
 */
MerchantAccount.prototype.isMigratedPaylevenBr = undefined;

