/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressPayload} from './AddressPayload';

/**
 * The MerchantProfilePayloadDoingBusinessAs model module.
 * @module model/MerchantProfilePayloadDoingBusinessAs
 * @version 1.0.0
 */
export class MerchantProfilePayloadDoingBusinessAs {
  /**
   * Constructs a new <code>MerchantProfilePayloadDoingBusinessAs</code>.
   * @alias module:model/MerchantProfilePayloadDoingBusinessAs
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>MerchantProfilePayloadDoingBusinessAs</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MerchantProfilePayloadDoingBusinessAs} obj Optional instance to populate.
   * @return {module:model/MerchantProfilePayloadDoingBusinessAs} The populated <code>MerchantProfilePayloadDoingBusinessAs</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new MerchantProfilePayloadDoingBusinessAs();
      if (data.hasOwnProperty('business_name'))
        obj.businessName = ApiClient.convertToType(data['business_name'], 'String');
      if (data.hasOwnProperty('tax_id'))
        obj.taxId = ApiClient.convertToType(data['tax_id'], 'String');
      if (data.hasOwnProperty('vat_id'))
        obj.vatId = ApiClient.convertToType(data['vat_id'], 'String');
      if (data.hasOwnProperty('website'))
        obj.website = ApiClient.convertToType(data['website'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = AddressPayload.constructFromObject(data['address']);
    }
    return obj;
  }
}

/**
 * Doing business as name
 * @member {String} businessName
 */
MerchantProfilePayloadDoingBusinessAs.prototype.businessName = undefined;

/**
 * Doing business as Tax ID
 * @member {String} taxId
 */
MerchantProfilePayloadDoingBusinessAs.prototype.taxId = undefined;

/**
 * Doing business as Vat ID
 * @member {String} vatId
 */
MerchantProfilePayloadDoingBusinessAs.prototype.vatId = undefined;

/**
 * Doing business as website
 * @member {String} website
 */
MerchantProfilePayloadDoingBusinessAs.prototype.website = undefined;

/**
 * Doing business as email
 * @member {String} email
 */
MerchantProfilePayloadDoingBusinessAs.prototype.email = undefined;

/**
 * @member {module:model/AddressPayload} address
 */
MerchantProfilePayloadDoingBusinessAs.prototype.address = undefined;

