/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {MandateResponse} from './MandateResponse';
import {PaymentInstrumentResponseCard} from './PaymentInstrumentResponseCard';

/**
 * The PaymentInstrumentResponse model module.
 * @module model/PaymentInstrumentResponse
 * @version 1.0.0
 */
export class PaymentInstrumentResponse {
  /**
   * Constructs a new <code>PaymentInstrumentResponse</code>.
   * Payment Instrument Response
   * @alias module:model/PaymentInstrumentResponse
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>PaymentInstrumentResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PaymentInstrumentResponse} obj Optional instance to populate.
   * @return {module:model/PaymentInstrumentResponse} The populated <code>PaymentInstrumentResponse</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PaymentInstrumentResponse();
      if (data.hasOwnProperty('token'))
        obj.token = ApiClient.convertToType(data['token'], 'String');
      if (data.hasOwnProperty('active'))
        obj.active = ApiClient.convertToType(data['active'], 'Boolean');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('card'))
        obj.card = PaymentInstrumentResponseCard.constructFromObject(data['card']);
      if (data.hasOwnProperty('mandate'))
        obj.mandate = MandateResponse.constructFromObject(data['mandate']);
      if (data.hasOwnProperty('created_at'))
        obj.createdAt = ApiClient.convertToType(data['created_at'], 'Date');
    }
    return obj;
  }
}

/**
 * Unique token identifying the saved payment card for a customer.
 * @member {String} token
 */
PaymentInstrumentResponse.prototype.token = undefined;

/**
 * Indicates whether the payment instrument is active and can be used for payments. To deactivate it, send a `DELETE` request to the resource endpoint.
 * @member {Boolean} active
 * @default true
 */
PaymentInstrumentResponse.prototype.active = true;

/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentInstrumentResponse.TypeEnum = {
  /**
   * value: "card"
   * @const
   */
  card: "card"
};
/**
 * Type of the payment instrument.
 * @member {module:model/PaymentInstrumentResponse.TypeEnum} type
 */
PaymentInstrumentResponse.prototype.type = undefined;

/**
 * @member {module:model/PaymentInstrumentResponseCard} card
 */
PaymentInstrumentResponse.prototype.card = undefined;

/**
 * @member {module:model/MandateResponse} mandate
 */
PaymentInstrumentResponse.prototype.mandate = undefined;

/**
 * Creation date of payment instrument. Response format expressed according to <a href=\"https://en.wikipedia.org/wiki/ISO_8601\" target=\"_blank\" rel=\"noopener\">ISO8601</a> code.
 * @member {Date} createdAt
 */
PaymentInstrumentResponse.prototype.createdAt = undefined;

