/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Permissions model module.
 * @module model/Permissions
 * @version 1.0.0
 */
export class Permissions {
  /**
   * Constructs a new <code>Permissions</code>.
   * User permissions
   * @alias module:model/Permissions
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Permissions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Permissions} obj Optional instance to populate.
   * @return {module:model/Permissions} The populated <code>Permissions</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Permissions();
      if (data.hasOwnProperty('create_moto_payments'))
        obj.createMotoPayments = ApiClient.convertToType(data['create_moto_payments'], 'Boolean');
      if (data.hasOwnProperty('full_transaction_history_view'))
        obj.fullTransactionHistoryView = ApiClient.convertToType(data['full_transaction_history_view'], 'Boolean');
      if (data.hasOwnProperty('refund_transactions'))
        obj.refundTransactions = ApiClient.convertToType(data['refund_transactions'], 'Boolean');
      if (data.hasOwnProperty('create_referral'))
        obj.createReferral = ApiClient.convertToType(data['create_referral'], 'Boolean');
    }
    return obj;
  }
}

/**
 * Create MOTO payments
 * @member {Boolean} createMotoPayments
 */
Permissions.prototype.createMotoPayments = undefined;

/**
 * Can view full merchant transaction history
 * @member {Boolean} fullTransactionHistoryView
 */
Permissions.prototype.fullTransactionHistoryView = undefined;

/**
 * Refund transactions
 * @member {Boolean} refundTransactions
 */
Permissions.prototype.refundTransactions = undefined;

/**
 * Create referral
 * @member {Boolean} createReferral
 */
Permissions.prototype.createReferral = undefined;

