/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AddressPayload} from './AddressPayload';

/**
 * The PersonalProfilePayload model module.
 * @module model/PersonalProfilePayload
 * @version 1.0.0
 */
export class PersonalProfilePayload {
  /**
   * Constructs a new <code>PersonalProfilePayload</code>.
   * Account&#x27;s personal profile.
   * @alias module:model/PersonalProfilePayload
   * @class
   * @param firstName {String} First name of the user
   * @param lastName {String} Last name of the user
   * @param dateOfBirth {Date} Date of birth
   * @param address {module:model/AddressPayload} 
   */
  constructor(firstName, lastName, dateOfBirth, address) {
    this.firstName = firstName;
    this.lastName = lastName;
    this.dateOfBirth = dateOfBirth;
    this.address = address;
  }

  /**
   * Constructs a <code>PersonalProfilePayload</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PersonalProfilePayload} obj Optional instance to populate.
   * @return {module:model/PersonalProfilePayload} The populated <code>PersonalProfilePayload</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new PersonalProfilePayload();
      if (data.hasOwnProperty('first_name'))
        obj.firstName = ApiClient.convertToType(data['first_name'], 'String');
      if (data.hasOwnProperty('last_name'))
        obj.lastName = ApiClient.convertToType(data['last_name'], 'String');
      if (data.hasOwnProperty('date_of_birth'))
        obj.dateOfBirth = ApiClient.convertToType(data['date_of_birth'], 'Date');
      if (data.hasOwnProperty('mobile_phone'))
        obj.mobilePhone = ApiClient.convertToType(data['mobile_phone'], 'String');
      if (data.hasOwnProperty('national_id'))
        obj.nationalId = ApiClient.convertToType(data['national_id'], 'String');
      if (data.hasOwnProperty('address'))
        obj.address = AddressPayload.constructFromObject(data['address']);
    }
    return obj;
  }
}

/**
 * First name of the user
 * @member {String} firstName
 */
PersonalProfilePayload.prototype.firstName = undefined;

/**
 * Last name of the user
 * @member {String} lastName
 */
PersonalProfilePayload.prototype.lastName = undefined;

/**
 * Date of birth
 * @member {Date} dateOfBirth
 */
PersonalProfilePayload.prototype.dateOfBirth = undefined;

/**
 * Mobile phone number
 * @member {String} mobilePhone
 */
PersonalProfilePayload.prototype.mobilePhone = undefined;

/**
 * National identification id. Country specific. Ex CPF &#40;Brazil&#41;, DNI (Spain), PESEL (Poland)
 * @member {String} nationalId
 */
PersonalProfilePayload.prototype.nationalId = undefined;

/**
 * @member {module:model/AddressPayload} address
 */
PersonalProfilePayload.prototype.address = undefined;

