/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Product model module.
 * @module model/Product
 * @version 1.0.0
 */
export class Product {
  /**
   * Constructs a new <code>Product</code>.
   * Details of the product for which the payment is made.
   * @alias module:model/Product
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Product</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Product} obj Optional instance to populate.
   * @return {module:model/Product} The populated <code>Product</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Product();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('vat_rate'))
        obj.vatRate = ApiClient.convertToType(data['vat_rate'], 'Number');
      if (data.hasOwnProperty('single_vat_amount'))
        obj.singleVatAmount = ApiClient.convertToType(data['single_vat_amount'], 'Number');
      if (data.hasOwnProperty('price_with_vat'))
        obj.priceWithVat = ApiClient.convertToType(data['price_with_vat'], 'Number');
      if (data.hasOwnProperty('vat_amount'))
        obj.vatAmount = ApiClient.convertToType(data['vat_amount'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('total_price'))
        obj.totalPrice = ApiClient.convertToType(data['total_price'], 'Number');
      if (data.hasOwnProperty('total_with_vat'))
        obj.totalWithVat = ApiClient.convertToType(data['total_with_vat'], 'Number');
    }
    return obj;
  }
}

/**
 * Name of the product from the merchant's catalog.
 * @member {String} name
 */
Product.prototype.name = undefined;

/**
 * Price of the product without VAT.
 * @member {Number} price
 */
Product.prototype.price = undefined;

/**
 * VAT rate applicable to the product.
 * @member {Number} vatRate
 */
Product.prototype.vatRate = undefined;

/**
 * Amount of the VAT for a single product item (calculated as the product of `price` and `vat_rate`, i.e. `single_vat_amount = price * vat_rate`).
 * @member {Number} singleVatAmount
 */
Product.prototype.singleVatAmount = undefined;

/**
 * Price of a single product item with VAT.
 * @member {Number} priceWithVat
 */
Product.prototype.priceWithVat = undefined;

/**
 * Total VAT amount for the purchase (calculated as the product of `single_vat_amount` and `quantity`, i.e. `vat_amount = single_vat_amount * quantity`).
 * @member {Number} vatAmount
 */
Product.prototype.vatAmount = undefined;

/**
 * Number of product items for the purchase.
 * @member {Number} quantity
 */
Product.prototype.quantity = undefined;

/**
 * Total price of the product items without VAT (calculated as the product of `price` and `quantity`, i.e. `total_price = price * quantity`).
 * @member {Number} totalPrice
 */
Product.prototype.totalPrice = undefined;

/**
 * Total price of the product items including VAT (calculated as the product of `price_with_vat` and `quantity`, i.e. `total_with_vat = price_with_vat * quantity`).
 * @member {Number} totalWithVat
 */
Product.prototype.totalWithVat = undefined;

