/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReceiptMerchantDataMerchantProfileAddress model module.
 * @module model/ReceiptMerchantDataMerchantProfileAddress
 * @version 1.0.0
 */
export class ReceiptMerchantDataMerchantProfileAddress {
  /**
   * Constructs a new <code>ReceiptMerchantDataMerchantProfileAddress</code>.
   * @alias module:model/ReceiptMerchantDataMerchantProfileAddress
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReceiptMerchantDataMerchantProfileAddress</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReceiptMerchantDataMerchantProfileAddress} obj Optional instance to populate.
   * @return {module:model/ReceiptMerchantDataMerchantProfileAddress} The populated <code>ReceiptMerchantDataMerchantProfileAddress</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReceiptMerchantDataMerchantProfileAddress();
      if (data.hasOwnProperty('address_line1'))
        obj.addressLine1 = ApiClient.convertToType(data['address_line1'], 'String');
      if (data.hasOwnProperty('city'))
        obj.city = ApiClient.convertToType(data['city'], 'String');
      if (data.hasOwnProperty('country'))
        obj.country = ApiClient.convertToType(data['country'], 'String');
      if (data.hasOwnProperty('country_en_name'))
        obj.countryEnName = ApiClient.convertToType(data['country_en_name'], 'String');
      if (data.hasOwnProperty('country_native_name'))
        obj.countryNativeName = ApiClient.convertToType(data['country_native_name'], 'String');
      if (data.hasOwnProperty('post_code'))
        obj.postCode = ApiClient.convertToType(data['post_code'], 'String');
      if (data.hasOwnProperty('landline'))
        obj.landline = ApiClient.convertToType(data['landline'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} addressLine1
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.addressLine1 = undefined;

/**
 * @member {String} city
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.city = undefined;

/**
 * @member {String} country
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.country = undefined;

/**
 * @member {String} countryEnName
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.countryEnName = undefined;

/**
 * @member {String} countryNativeName
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.countryNativeName = undefined;

/**
 * @member {String} postCode
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.postCode = undefined;

/**
 * @member {String} landline
 */
ReceiptMerchantDataMerchantProfileAddress.prototype.landline = undefined;

