/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReceiptTransactionVatRates model module.
 * @module model/ReceiptTransactionVatRates
 * @version 1.0.0
 */
export class ReceiptTransactionVatRates {
  /**
   * Constructs a new <code>ReceiptTransactionVatRates</code>.
   * @alias module:model/ReceiptTransactionVatRates
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReceiptTransactionVatRates</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReceiptTransactionVatRates} obj Optional instance to populate.
   * @return {module:model/ReceiptTransactionVatRates} The populated <code>ReceiptTransactionVatRates</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReceiptTransactionVatRates();
      if (data.hasOwnProperty('gross'))
        obj.gross = ApiClient.convertToType(data['gross'], 'Number');
      if (data.hasOwnProperty('net'))
        obj.net = ApiClient.convertToType(data['net'], 'Number');
      if (data.hasOwnProperty('rate'))
        obj.rate = ApiClient.convertToType(data['rate'], 'Number');
      if (data.hasOwnProperty('vat'))
        obj.vat = ApiClient.convertToType(data['vat'], 'Number');
    }
    return obj;
  }
}

/**
 * Gross
 * @member {Number} gross
 */
ReceiptTransactionVatRates.prototype.gross = undefined;

/**
 * Net
 * @member {Number} net
 */
ReceiptTransactionVatRates.prototype.net = undefined;

/**
 * Rate
 * @member {Number} rate
 */
ReceiptTransactionVatRates.prototype.rate = undefined;

/**
 * Vat
 * @member {Number} vat
 */
ReceiptTransactionVatRates.prototype.vat = undefined;

