/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The ReceiptTransactionProducts model module.
 * @module model/ReceiptTransactionProducts
 * @version 1.0.0
 */
export class ReceiptTransactionProducts {
  /**
   * Constructs a new <code>ReceiptTransactionProducts</code>.
   * @alias module:model/ReceiptTransactionProducts
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>ReceiptTransactionProducts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ReceiptTransactionProducts} obj Optional instance to populate.
   * @return {module:model/ReceiptTransactionProducts} The populated <code>ReceiptTransactionProducts</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new ReceiptTransactionProducts();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('price'))
        obj.price = ApiClient.convertToType(data['price'], 'Number');
      if (data.hasOwnProperty('quantity'))
        obj.quantity = ApiClient.convertToType(data['quantity'], 'Number');
      if (data.hasOwnProperty('total_price'))
        obj.totalPrice = ApiClient.convertToType(data['total_price'], 'Number');
    }
    return obj;
  }
}

/**
 * Product name.
 * @member {String} name
 */
ReceiptTransactionProducts.prototype.name = undefined;

/**
 * Product description.
 * @member {String} description
 */
ReceiptTransactionProducts.prototype.description = undefined;

/**
 * Product price.
 * @member {Number} price
 */
ReceiptTransactionProducts.prototype.price = undefined;

/**
 * Product quantity.
 * @member {Number} quantity
 */
ReceiptTransactionProducts.prototype.quantity = undefined;

/**
 * Quantity x product price.
 * @member {Number} totalPrice
 */
ReceiptTransactionProducts.prototype.totalPrice = undefined;

