/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {AmountEvent} from './AmountEvent';
import {EventID} from './EventID';
import {EventStatus} from './EventStatus';
import {EventType} from './EventType';
import {TimestampEvent} from './TimestampEvent';

/**
 * The TransactionEvent model module.
 * @module model/TransactionEvent
 * @version 1.0.0
 */
export class TransactionEvent {
  /**
   * Constructs a new <code>TransactionEvent</code>.
   * Details of a transaction event.
   * @alias module:model/TransactionEvent
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionEvent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionEvent} obj Optional instance to populate.
   * @return {module:model/TransactionEvent} The populated <code>TransactionEvent</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionEvent();
      if (data.hasOwnProperty('id'))
        obj.id = EventID.constructFromObject(data['id']);
      if (data.hasOwnProperty('event_type'))
        obj.eventType = EventType.constructFromObject(data['event_type']);
      if (data.hasOwnProperty('status'))
        obj.status = EventStatus.constructFromObject(data['status']);
      if (data.hasOwnProperty('amount'))
        obj.amount = AmountEvent.constructFromObject(data['amount']);
      if (data.hasOwnProperty('due_date'))
        obj.dueDate = ApiClient.convertToType(data['due_date'], 'Date');
      if (data.hasOwnProperty('date'))
        obj._date = ApiClient.convertToType(data['date'], 'Date');
      if (data.hasOwnProperty('installment_number'))
        obj.installmentNumber = ApiClient.convertToType(data['installment_number'], 'Number');
      if (data.hasOwnProperty('timestamp'))
        obj.timestamp = TimestampEvent.constructFromObject(data['timestamp']);
    }
    return obj;
  }
}

/**
 * @member {module:model/EventID} id
 */
TransactionEvent.prototype.id = undefined;

/**
 * @member {module:model/EventType} eventType
 */
TransactionEvent.prototype.eventType = undefined;

/**
 * @member {module:model/EventStatus} status
 */
TransactionEvent.prototype.status = undefined;

/**
 * @member {module:model/AmountEvent} amount
 */
TransactionEvent.prototype.amount = undefined;

/**
 * Date when the transaction event is due to occur.
 * @member {Date} dueDate
 */
TransactionEvent.prototype.dueDate = undefined;

/**
 * Date when the transaction event occurred.
 * @member {Date} _date
 */
TransactionEvent.prototype._date = undefined;

/**
 * Consequtive number of the installment that is paid. Applicable only payout events, i.e. `event_type = PAYOUT`.
 * @member {Number} installmentNumber
 */
TransactionEvent.prototype.installmentNumber = undefined;

/**
 * @member {module:model/TimestampEvent} timestamp
 */
TransactionEvent.prototype.timestamp = undefined;

