/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The TransactionMixinHistory model module.
 * @module model/TransactionMixinHistory
 * @version 1.0.0
 */
export class TransactionMixinHistory {
  /**
   * Constructs a new <code>TransactionMixinHistory</code>.
   * @alias module:model/TransactionMixinHistory
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>TransactionMixinHistory</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TransactionMixinHistory} obj Optional instance to populate.
   * @return {module:model/TransactionMixinHistory} The populated <code>TransactionMixinHistory</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new TransactionMixinHistory();
      if (data.hasOwnProperty('product_summary'))
        obj.productSummary = ApiClient.convertToType(data['product_summary'], 'String');
      if (data.hasOwnProperty('payouts_total'))
        obj.payoutsTotal = ApiClient.convertToType(data['payouts_total'], 'Number');
      if (data.hasOwnProperty('payouts_received'))
        obj.payoutsReceived = ApiClient.convertToType(data['payouts_received'], 'Number');
      if (data.hasOwnProperty('payout_plan'))
        obj.payoutPlan = ApiClient.convertToType(data['payout_plan'], 'String');
    }
    return obj;
  }
}

/**
 * Short description of the payment. The value is taken from the `description` property of the related checkout resource.
 * @member {String} productSummary
 */
TransactionMixinHistory.prototype.productSummary = undefined;

/**
 * Total number of payouts to the registered user specified in the `user` property.
 * @member {Number} payoutsTotal
 */
TransactionMixinHistory.prototype.payoutsTotal = undefined;

/**
 * Number of payouts that are made to the registered user specified in the `user` property.
 * @member {Number} payoutsReceived
 */
TransactionMixinHistory.prototype.payoutsReceived = undefined;

/**
 * Allowed values for the <code>payoutPlan</code> property.
 * @enum {String}
 * @readonly
 */
TransactionMixinHistory.PayoutPlanEnum = {
  /**
   * value: "SINGLE_PAYMENT"
   * @const
   */
  SINGLE_PAYMENT: "SINGLE_PAYMENT",

  /**
   * value: "TRUE_INSTALLMENT"
   * @const
   */
  TRUE_INSTALLMENT: "TRUE_INSTALLMENT",

  /**
   * value: "ACCELERATED_INSTALLMENT"
   * @const
   */
  ACCELERATED_INSTALLMENT: "ACCELERATED_INSTALLMENT"
};
/**
 * Payout plan of the registered user at the time when the transaction was made.
 * @member {module:model/TransactionMixinHistory.PayoutPlanEnum} payoutPlan
 */
TransactionMixinHistory.prototype.payoutPlan = undefined;

