/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SumUpRestApi);
  }
}(this, function(expect, SumUpRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('AddressWithDetails', function() {
      beforeEach(function() {
        instance = new SumUpRestApi.AddressWithDetails();
      });

      it('should create an instance of AddressWithDetails', function() {
        // TODO: update the code to test AddressWithDetails
        expect(instance).to.be.a(SumUpRestApi.AddressWithDetails);
      });

      it('should have the property addressLine1 (base name: "address_line1")', function() {
        // TODO: update the code to test the property addressLine1
        expect(instance).to.have.property('addressLine1');
        // expect(instance.addressLine1).to.be(expectedValueLiteral);
      });

      it('should have the property addressLine2 (base name: "address_line2")', function() {
        // TODO: update the code to test the property addressLine2
        expect(instance).to.have.property('addressLine2');
        // expect(instance.addressLine2).to.be(expectedValueLiteral);
      });

      it('should have the property city (base name: "city")', function() {
        // TODO: update the code to test the property city
        expect(instance).to.have.property('city');
        // expect(instance.city).to.be(expectedValueLiteral);
      });

      it('should have the property country (base name: "country")', function() {
        // TODO: update the code to test the property country
        expect(instance).to.have.property('country');
        // expect(instance.country).to.be(expectedValueLiteral);
      });

      it('should have the property regionId (base name: "region_id")', function() {
        // TODO: update the code to test the property regionId
        expect(instance).to.have.property('regionId');
        // expect(instance.regionId).to.be(expectedValueLiteral);
      });

      it('should have the property regionName (base name: "region_name")', function() {
        // TODO: update the code to test the property regionName
        expect(instance).to.have.property('regionName');
        // expect(instance.regionName).to.be(expectedValueLiteral);
      });

      it('should have the property regionCode (base name: "region_code")', function() {
        // TODO: update the code to test the property regionCode
        expect(instance).to.have.property('regionCode');
        // expect(instance.regionCode).to.be(expectedValueLiteral);
      });

      it('should have the property postCode (base name: "post_code")', function() {
        // TODO: update the code to test the property postCode
        expect(instance).to.have.property('postCode');
        // expect(instance.postCode).to.be(expectedValueLiteral);
      });

      it('should have the property landline (base name: "landline")', function() {
        // TODO: update the code to test the property landline
        expect(instance).to.have.property('landline');
        // expect(instance.landline).to.be(expectedValueLiteral);
      });

      it('should have the property firstName (base name: "first_name")', function() {
        // TODO: update the code to test the property firstName
        expect(instance).to.have.property('firstName');
        // expect(instance.firstName).to.be(expectedValueLiteral);
      });

      it('should have the property lastName (base name: "last_name")', function() {
        // TODO: update the code to test the property lastName
        expect(instance).to.have.property('lastName');
        // expect(instance.lastName).to.be(expectedValueLiteral);
      });

      it('should have the property company (base name: "company")', function() {
        // TODO: update the code to test the property company
        expect(instance).to.have.property('company');
        // expect(instance.company).to.be(expectedValueLiteral);
      });

      it('should have the property countryDetails (base name: "country_details")', function() {
        // TODO: update the code to test the property countryDetails
        expect(instance).to.have.property('countryDetails');
        // expect(instance.countryDetails).to.be(expectedValueLiteral);
      });

      it('should have the property timeoffsetDetails (base name: "timeoffset_details")', function() {
        // TODO: update the code to test the property timeoffsetDetails
        expect(instance).to.have.property('timeoffsetDetails');
        // expect(instance.timeoffsetDetails).to.be(expectedValueLiteral);
      });

      it('should have the property stateId (base name: "state_id")', function() {
        // TODO: update the code to test the property stateId
        expect(instance).to.have.property('stateId');
        // expect(instance.stateId).to.be(expectedValueLiteral);
      });

    });
  });

}));
