/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SumUpRestApi);
  }
}(this, function(expect, SumUpRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('BankAccount', function() {
      beforeEach(function() {
        instance = new SumUpRestApi.BankAccount();
      });

      it('should create an instance of BankAccount', function() {
        // TODO: update the code to test BankAccount
        expect(instance).to.be.a(SumUpRestApi.BankAccount);
      });

      it('should have the property bankCode (base name: "bank_code")', function() {
        // TODO: update the code to test the property bankCode
        expect(instance).to.have.property('bankCode');
        // expect(instance.bankCode).to.be(expectedValueLiteral);
      });

      it('should have the property branchCode (base name: "branch_code")', function() {
        // TODO: update the code to test the property branchCode
        expect(instance).to.have.property('branchCode');
        // expect(instance.branchCode).to.be(expectedValueLiteral);
      });

      it('should have the property swift (base name: "swift")', function() {
        // TODO: update the code to test the property swift
        expect(instance).to.have.property('swift');
        // expect(instance.swift).to.be(expectedValueLiteral);
      });

      it('should have the property accountNumber (base name: "account_number")', function() {
        // TODO: update the code to test the property accountNumber
        expect(instance).to.have.property('accountNumber');
        // expect(instance.accountNumber).to.be(expectedValueLiteral);
      });

      it('should have the property iban (base name: "iban")', function() {
        // TODO: update the code to test the property iban
        expect(instance).to.have.property('iban');
        // expect(instance.iban).to.be(expectedValueLiteral);
      });

      it('should have the property accountType (base name: "account_type")', function() {
        // TODO: update the code to test the property accountType
        expect(instance).to.have.property('accountType');
        // expect(instance.accountType).to.be(expectedValueLiteral);
      });

      it('should have the property accountCategory (base name: "account_category")', function() {
        // TODO: update the code to test the property accountCategory
        expect(instance).to.have.property('accountCategory');
        // expect(instance.accountCategory).to.be(expectedValueLiteral);
      });

      it('should have the property accountHolderName (base name: "account_holder_name")', function() {
        // TODO: update the code to test the property accountHolderName
        expect(instance).to.have.property('accountHolderName');
        // expect(instance.accountHolderName).to.be(expectedValueLiteral);
      });

      it('should have the property status (base name: "status")', function() {
        // TODO: update the code to test the property status
        expect(instance).to.have.property('status');
        // expect(instance.status).to.be(expectedValueLiteral);
      });

      it('should have the property primary (base name: "primary")', function() {
        // TODO: update the code to test the property primary
        expect(instance).to.have.property('primary');
        // expect(instance.primary).to.be(expectedValueLiteral);
      });

      it('should have the property createdAt (base name: "created_at")', function() {
        // TODO: update the code to test the property createdAt
        expect(instance).to.have.property('createdAt');
        // expect(instance.createdAt).to.be(expectedValueLiteral);
      });

      it('should have the property bankName (base name: "bank_name")', function() {
        // TODO: update the code to test the property bankName
        expect(instance).to.have.property('bankName');
        // expect(instance.bankName).to.be(expectedValueLiteral);
      });

    });
  });

}));
