/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SumUpRestApi);
  }
}(this, function(expect, SumUpRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Card', function() {
      beforeEach(function() {
        instance = new SumUpRestApi.Card();
      });

      it('should create an instance of Card', function() {
        // TODO: update the code to test Card
        expect(instance).to.be.a(SumUpRestApi.Card);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property _number (base name: "number")', function() {
        // TODO: update the code to test the property _number
        expect(instance).to.have.property('_number');
        // expect(instance._number).to.be(expectedValueLiteral);
      });

      it('should have the property expiryYear (base name: "expiry_year")', function() {
        // TODO: update the code to test the property expiryYear
        expect(instance).to.have.property('expiryYear');
        // expect(instance.expiryYear).to.be(expectedValueLiteral);
      });

      it('should have the property expiryMonth (base name: "expiry_month")', function() {
        // TODO: update the code to test the property expiryMonth
        expect(instance).to.have.property('expiryMonth');
        // expect(instance.expiryMonth).to.be(expectedValueLiteral);
      });

      it('should have the property cvv (base name: "cvv")', function() {
        // TODO: update the code to test the property cvv
        expect(instance).to.have.property('cvv');
        // expect(instance.cvv).to.be(expectedValueLiteral);
      });

      it('should have the property zipCode (base name: "zip_code")', function() {
        // TODO: update the code to test the property zipCode
        expect(instance).to.have.property('zipCode');
        // expect(instance.zipCode).to.be(expectedValueLiteral);
      });

      it('should have the property last4Digits (base name: "last_4_digits")', function() {
        // TODO: update the code to test the property last4Digits
        expect(instance).to.have.property('last4Digits');
        // expect(instance.last4Digits).to.be(expectedValueLiteral);
      });

      it('should have the property type (base name: "type")', function() {
        // TODO: update the code to test the property type
        expect(instance).to.have.property('type');
        // expect(instance.type).to.be(expectedValueLiteral);
      });

    });
  });

}));
