/*
 * SumUp REST API
 * SumUp’s REST API operates with `application/json` HTTP requests and response. The request bodies are sent through resource-oriented URLs and use the standard HTTP response codes.  For testing our APIs, please <a href='https://cloud.crm.sumup.com/sumup-developers-contact-form'>contact us</a> for a test account.   When you receive your test account you can create your <a href='https://developer.sumup.com/docs/register-app/#3-create-oauth-client-credentials' target='_blank'>client credentials</a> and process different requests with real payment instruments, without charging them.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.34
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SumUpRestApi);
  }
}(this, function(expect, SumUpRestApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('TransactionMixinHistory', function() {
      beforeEach(function() {
        instance = new SumUpRestApi.TransactionMixinHistory();
      });

      it('should create an instance of TransactionMixinHistory', function() {
        // TODO: update the code to test TransactionMixinHistory
        expect(instance).to.be.a(SumUpRestApi.TransactionMixinHistory);
      });

      it('should have the property productSummary (base name: "product_summary")', function() {
        // TODO: update the code to test the property productSummary
        expect(instance).to.have.property('productSummary');
        // expect(instance.productSummary).to.be(expectedValueLiteral);
      });

      it('should have the property payoutsTotal (base name: "payouts_total")', function() {
        // TODO: update the code to test the property payoutsTotal
        expect(instance).to.have.property('payoutsTotal');
        // expect(instance.payoutsTotal).to.be(expectedValueLiteral);
      });

      it('should have the property payoutsReceived (base name: "payouts_received")', function() {
        // TODO: update the code to test the property payoutsReceived
        expect(instance).to.have.property('payoutsReceived');
        // expect(instance.payoutsReceived).to.be(expectedValueLiteral);
      });

      it('should have the property payoutPlan (base name: "payout_plan")', function() {
        // TODO: update the code to test the property payoutPlan
        expect(instance).to.have.property('payoutPlan');
        // expect(instance.payoutPlan).to.be(expectedValueLiteral);
      });

    });
  });

}));
